[package]
name = "rize"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bcrypt = "0.8"
jsonwebtoken = "7"
serde = { version = "1", features = ["derive"] }
uuid = "0.8"
chrono = "0.4"
actix-web = "3"
actix-rt = "1"
